/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,jsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
            },
            colors: {
                primary: {
                    50:  '#eef2ff',
                    100: '#e0e7ff',
                    200: '#c7d2fe',
                    300: '#a5b4fc',
                    400: '#818cf8',
                    500: '#6366f1',
                    600: '#4f46e5',
                    700: '#4338ca',
                    800: '#3730a3',
                    900: '#312e81',
                    950: '#1e1b4b',
                },
                accent: {
                    50:  '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f76c35',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                },
                secondary: {
                    50:  '#fdf4ff',
                    100: '#fae8ff',
                    200: '#f5d0fe',
                    300: '#f0abfc',
                    400: '#e879f9',
                    500: '#d946ef',
                    600: '#c026d3',
                    700: '#a21caf',
                    800: '#86198f',
                    900: '#701a75',
                },
                brand: {
                    dark: '#0f172a',
                    nav:  '#111827',
                    card: '#1e2340',
                    border: '#2d3155',
                },
                neutral: {
                    50:  '#f9fafb',
                    100: '#f3f4f6',
                    200: '#e5e7eb',
                    300: '#d1d5db',
                    400: '#9ca3af',
                    500: '#6b7280',
                    600: '#4b5563',
                    700: '#374151',
                    800: '#1f2937',
                    900: '#111827',
                    950: '#030712',
                },
            },
            animation: {
                'fade-in':      'fadeIn 0.5s ease-in-out both',
                'fade-up':      'fadeUp 0.5s ease-out both',
                'slide-in':     'slideIn 0.35s cubic-bezier(0.4,0,0.2,1) both',
                'slide-down':   'slideDown 0.3s ease-out both',
                'slide-left':   'slideLeft 0.4s ease-out both',
                'bounce-subtle':'bounceSubtle 2s infinite',
                'float':        'float 4s ease-in-out infinite',
                'shimmer':      'shimmer 1.6s linear infinite',
                'pulse-glow':   'pulseGlow 2s ease-in-out infinite',
                'scale-in':     'scaleIn 0.25s cubic-bezier(0.34,1.56,0.64,1) both',
                'progress':     'progress 3s linear forwards',
                'spin-slow':    'spin 3s linear infinite',
            },
            keyframes: {
                fadeIn:      { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
                fadeUp:      { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
                slideIn:     { '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
                slideDown:   { '0%': { transform: 'translateY(-12px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
                slideLeft:   { '0%': { transform: 'translateX(-100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
                bounceSubtle:{ '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-3px)' } },
                float:       { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
                shimmer:     { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
                pulseGlow:   { '0%, 100%': { opacity: '1', boxShadow: '0 0 20px rgba(99,102,241,0.4)' }, '50%': { opacity: '0.85', boxShadow: '0 0 40px rgba(99,102,241,0.7)' } },
                scaleIn:     { '0%': { transform: 'scale(0.8)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
                progress:    { '0%': { width: '100%' }, '100%': { width: '0%' } },
            },
            boxShadow: {
                'glow':    '0 0 20px rgba(99,102,241,0.35)',
                'glow-lg': '0 0 40px rgba(99,102,241,0.5)',
                'card':    '0 4px 24px -4px rgba(0,0,0,0.12)',
                'card-lg': '0 12px 40px -8px rgba(0,0,0,0.18)',
                'nav':     '0 2px 24px -2px rgba(0,0,0,0.25)',
            },
            backdropBlur: {
                xs: '2px',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
            },
        },
    },
    plugins: [],
}
